#!/usr/bin/env just --justfile

set dotenv-load

name := anonventbot

lock:
	npm i --package-lock-only

install:
	npm ci

start:
	pm2 start bot.js --name {{name}}

stop:
	pm2 stop {{name}}

restart:
	pm2 restart {{name}}

full-start: lock install start
