#!/usr/bin/env just --justfile

set dotenv-load

name := "anonventbot"

default:
    @just --list

# regenerate package-lock.json
lock:
	npm i --package-lock-only

# install dependencies
install:
	npm ci

# start the bot
start:
	pm2 start bot.js --name {{name}}

# stop the bot
stop:
	pm2 stop {{name}}

# restart the bot
restart:
	pm2 restart {{name}}

# lock, install, and start the bot
full-start: lock install start
